### ISSUE TITLE
what are Sn and SN?

### ISSUE THREAD

**Issue by seongq** [gladia-research-group/multi-source-diffusion-models#2]
Hello.
What are Sn and SN?
I think these are neural network for score.
Then, for separation, Should I tran N neural networks?

**Comment by EmilianPostolache** [comment]
As outlined in the paper (https://arxiv.org/abs/2305.10427), Sn and SN are the components of the score network related to the score prediction of the n-th and N-th source. So for MSDM you train a single network. That part is implemented in the  [differential_with_dirac](https://github.com/gladia-research-group/multi-source-diffusion-models/blob/main/main/separation.py#L85) function in [main/separation.py](https://github.com/gladia-research-group/multi-source-diffusion-models/blob/main/main/separation.py).
