### ISSUE TITLE
Test data sample rate problem

### ISSUE THREAD

**Issue by EmilianPostolache** [gladia-research-group/multi-source-diffusion-models#4]
When using the test data linked in this [page](https://github.com/gladia-research-group/multi-source-diffusion-models/blob/main/data/README.md) ([download link](https://drive.google.com/file/d/1LOiCTEuOkfCCgzgfdf82ZLSe9pfNPjD7/view?usp=share_link)) and evaluates a separation experiment like [eval_msdm_dirac.yaml](https://github.com/gladia-research-group/multi-source-diffusion-models/blob/main/exp/eval_msdm_dirac.yaml) one gets `AssertionError: sample rate 44100 is different from target sample rate 22050`. Shouldn't resampling be done when using such data?

**Comment by giorgio-mariani** [comment]
I think there was a mix-up with the data. I will upload the data with the correct sample-rate and update the download link.
